#!/usr/bin/perl

# analyze
#   Do all of our analysis and print out the results.

my $data = "data/aggregate-data.tsv";

print "LANGUAGES and TOOLS\n";
analyzeLanguage("3D Printing");
analyzeLanguage("Adobe");
analyzeLanguage("Alice");
analyzeLanguage("App Inventor");
analyzeLanguage("Arduino");
analyzeLanguage("Blender");
analyzeLanguage("Blockly");
analyzeLanguage("C");
analyzeLanguage("C#");
analyzeLanguage("C++");
analyzeLanguage("CAD");
analyzeLanguage("CSS");
analyzeLanguage("Flash");
analyzeLanguage("GameMaker");
analyzeLanguage("GameSalad");
analyzeLanguage("HTML");
analyzeLanguage("Java");
analyzeLanguage("JavaScript");
analyzeLanguage("LEGO");
analyzeLanguage("Lua");
analyzeLanguage("Maya");
analyzeLanguage("Minecraft");
analyzeLanguage("PHP");
analyzeLanguage("Processing");
analyzeLanguage("Python");
analyzeLanguage("Scratch");
analyzeLanguage("Snap");
analyzeLanguage("Source 2");
analyzeLanguage("Stencyl");
analyzeLanguage("Unity");
analyzeLanguage("Unreal Engine");

print "\n";
print "RARE LANGUAGES AND TOOLS\n";
analyzeLanguage("3D Studio");
analyzeLanguage("Code Studio");
analyzeLanguage("ComicLife");
analyzeLanguage("Construct");
analyzeLanguage("Kerbal Space Program");
analyzeLanguage("Kodable");
analyzeLanguage("Lightbot");
analyzeLanguage("Logo");
analyzeLanguage("Matlab");
analyzeLanguage("MicroWorlds");
analyzeLanguage("Multimedia Fusion");
analyzeLanguage("Quorum");
analyzeLanguage("R");
analyzeLanguage("RPG Maker");
analyzeLanguage("Ruby on Rails");
analyzeLanguage("Sketchup");
analyzeLanguage("SQL");
analyzeLanguage("Toon Boom Harmony");
analyzeLanguage("TrackMania United");
analyzeLanguage("West Point Bridge Designer");
analyzeLanguage("Windows Movie Maker");
analyzeLanguage("ZBrush");

sub analyzeLanguage($) {
  my $language = shift; # This is how you say "grab an argument" in Perl
  print "$language: ";
  $result = `colgrep "$language" 6 "$data" | wc -l`;
  print $result;
}

