#!/usr/bin/perl

# extract-google-urls
#   A quick hack to extract URLs from a Google result page

while (my $line = <STDIN>) {
  chomp($line);
  # Here are URLs in results from lynx
  while ($line =~ m/<a href="\/url\?q=([^"]*?)\&amp;[^"]*">(.*?)<\/a>/g) {
    my ($url,$title) = ($1,$2);
    $title =~ s/<[^>]*>//g;
    if ($title) { print "$url\t$title\n"; }
  } # while
  # Here are URLs in results from simulated Firefox
  while ($line =~ m/<a href="([^"]*)" onmousedown[^>]*>(.*?)<\/a>/g) {
    my ($url,$title) = ($1,$2);
    $title =~ s/<[^>]*>//g;
    if ($title) { print "$url\t$title\n"; }
  } # while
}
