#!/usr/bin/perl

# extract-google-urls
#   A quick hack to extract URLs from a Google result page

while (my $line = <STDIN>) {
  chomp($line);
  # Here are URLs in results from lynx
  while ($line =~ m/<a href="\/url\?q=([^"]*?)\&amp;[^"]*">(.*?)<\/a>/g) {
    my ($url,$title) = ($1,$2);
    $title = cleantitle($title);
    if ($title) { print "$url\t$title\n"; }
  } # while
  # Here are URLs in results from simulated Firefox
  while ($line =~ m/<a href="([^"]*)" onmousedown[^>]*>(.*?)<\/a>/g) {
    my ($url,$title) = ($1,$2);
    $title = cleantitle($title);
    if ($title) { print "$url\t$title\n"; }
  } # while
}

sub cleantitle($)
{
  my $title = shift;
  $title =~ s/<[^>]*>//g;
  $title =~ s/\&#39;/'/g;
  return $title;
}

    $title =~ s/\&#39;/'/g;

